mkl:
  - 2025
# Default: on osx-arm64 — only openmpi; others — nompi/mpich
mpi:
  - openmpi                # [osx and arm64]
  - nompi                  # [not (osx and arm64)]
  - mpich                  # [not (osx and arm64) and not win]
