{% set version = "3.5.0" %}
{% set variant = "openblas" %}

package:
  name: arpack
  version: {{ version }}

source:
  fn: arpack-{{ version }}.tar.gz
  url: https://github.com/opencollab/arpack-ng/archive/{{ version }}.tar.gz
  sha256: 50f7a3e3aec2e08e732a487919262238f8504c3ef927246ec3495617dde81239

build:
  number: 200
  features:
    - blas_{{ variant }}
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - gcc  # [unix]
    - cmake
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

  run:
    - libgfortran
    - libgcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

test:
  requirements:
    - python
  commands:
    - test -f ${PREFIX}/lib/libarpack.a  # [unix]
    - python -c "import ctypes; ctypes.cdll['$PREFIX/lib/libarpack.so']"  # [linux]
    - python -c "import ctypes; ctypes.cdll['$PREFIX/lib/libarpack.dylib']"  # [osx]

about:
  home: https://github.com/opencollab/arpack-ng
  license: BSD 3-Clause
  license_file: COPYING
  summary: Fortran77 subroutines designed to solve large scale eigenvalue problems

extra:
  recipe-maintainers:
    - jschueller
