# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: generic

os: osx

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ae8WJyvlorDueJcwg28/SghParjkh4GTeH1bI61rtXExKdrhsx7Yb8jBqXQ/UbEe+tedEE0dQ/Nh/aqk635OimVHCVBWnMpBp5jEfRdcWdmncXdV6lL6mHJlrEtE73pKgiPyVlgqCHQHhMHxjTTFimU+zpzQqWYBywYpSdoDK7pG3h8dr238AcZY1h3H9KbCQcGCWOasJTUXHwlT8o558NLGxiPXA+MSQNXe6Yw+Kq7rCxG1QIZOCi/vMOCFwrCGbz63fGfr1m9YFK//+KNhQIv3ZfoIZg8Rz3ia2xq5Xo7KvlF/7zIgX6KJpA+82iDpimNH6TKZxsV2BsFG1m/TrNr0vGq1xk12DWE0IcYBat+tgkRhP2yKU9jAD4uUlQv25LBXk4KCRMuhxOof/dJwZVd6yy/hLEt5F+2YdRfhgYtbfUsf5F0OtQwwcep3iyZIesYg6RPdzUtWLyEm/IhX1dwf63/pVbQOSktFjTmcd+KVSCjC8o680Nag5R5guFnbeu5xycLupscKV+YPbjjJPtbXRYPKt0h1M1t1BGfpEJDE8l4VMZkUA6uZ8iKfj3RDYTMGVOzyYAdiob1j7ZVtaxvT7nM6PH5quqmY85ZRAnr4M/w+NNI1XLtzK7FtYZpYDBRpQWDBS424S8q89I8yjwt0PYp9l4AzzDum6LR16do="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
