travis:
  secure:
    BINSTAR_TOKEN: SVxlLYc92RPzOiQSDWyK+6ITCAlek18Kvh5IxqbD5jA1RkxtZusN4obOxlcOBecM0gAOgA8T3QgUgf1xaWg2m0mvRvUvBnVGA1vBpvlsOLgQaHy4XtiMOeoe6SwfVr/E+xTJpO0UX3RP6VDxUlTnMs6AzHD/aEtpadKgDSefaELxVI6BBVZ2/qzh0gGN7CVp1e9hO3qZ+qBDOf3EOqp/R2D9pAw/3qro7xFAfyqQL7GzKi3xrKPGKjhtd70y0PLP1tyD7JM1eZietZyLFEEDTbgeQPP/w5IcIzbpyk9uLAWfNMbwxaJsbeC4Os4hLNI138EJztL0KUKF2wdUWf7iT5EfROiAPnwFU20RjohHZwThockxqYOBhNwva3zjaoNTqBhw5x60Ruq8M40Ifsc7fxy9nkgdAoYHerfxN08nuz6TcKgJpS/hwTVUrwlL6sPYw8GiFAveyZPAnTw3+5SLOqvWFG7kAakVpM/V6O6gN7ySrAMJrZgIeCjtgYfyQFyjXWU62OLa+I02auFG0xP7ZzaZLjCmvXR20tAA8XIs1/82GQycJbw9/82eq7hmG50nvQkSykRR2JqLkJMazPCEewxOBuBaDBmctK+VguydW4/mP1M7bZrXWDrVEPIXCPp84+GVLwp3sWe43EEp+bydY49lGgt4utcD3LPDmmITAmw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
